<?php

namespace Zittme\Modules\Commerce\Models;

/**
 * 국가별 행정구역 — 배송지 입력과 지역 추가 배송비가 함께 쓴다.
 *
 * 운영자와 구매자가 같은 목록에서 같은 코드를 고르게 하려고 둔다. 이름을 손으로
 * 적게 하면 표기가 갈려(Mexico / México / CDMX) 조용히 어긋난다.
 *
 * 이름은 언어 파일이 아니라 여기에 둔다. 대부분 번역할 것이 없는 고유명사이고,
 * 언어 파일로 빼면 나라를 하나 추가할 때마다 12개 파일을 건드려야 한다.
 * 현재 언어의 이름이 없으면 영문으로 떨어진다.
 *
 * 목록이 없는 나라는 행정구역을 자유 입력으로 받고 배송비 판정에는 쓰지 않는다.
 */
class Region
{
	/**
	 * 코드 => [언어 => 이름]. 영문(en)은 반드시 넣는다 (기본값이 된다).
	 */
	public const REGIONS = [
		'KR' => [
			'KR-11' => ['ko' => '서울', 'en' => 'Seoul'],
			'KR-26' => ['ko' => '부산', 'en' => 'Busan'],
			'KR-27' => ['ko' => '대구', 'en' => 'Daegu'],
			'KR-28' => ['ko' => '인천', 'en' => 'Incheon'],
			'KR-29' => ['ko' => '광주', 'en' => 'Gwangju'],
			'KR-30' => ['ko' => '대전', 'en' => 'Daejeon'],
			'KR-31' => ['ko' => '울산', 'en' => 'Ulsan'],
			'KR-50' => ['ko' => '세종', 'en' => 'Sejong'],
			'KR-41' => ['ko' => '경기', 'en' => 'Gyeonggi'],
			'KR-42' => ['ko' => '강원', 'en' => 'Gangwon'],
			'KR-43' => ['ko' => '충북', 'en' => 'Chungbuk'],
			'KR-44' => ['ko' => '충남', 'en' => 'Chungnam'],
			'KR-45' => ['ko' => '전북', 'en' => 'Jeonbuk'],
			'KR-46' => ['ko' => '전남', 'en' => 'Jeonnam'],
			'KR-47' => ['ko' => '경북', 'en' => 'Gyeongbuk'],
			'KR-48' => ['ko' => '경남', 'en' => 'Gyeongnam'],
			'KR-49' => ['ko' => '제주', 'en' => 'Jeju'],
		],

		'US' => [
			'US-AL' => ['en' => 'Alabama', 'ko' => '앨라배마'],
			'US-AK' => ['en' => 'Alaska', 'ko' => '알래스카'],
			'US-AZ' => ['en' => 'Arizona', 'ko' => '애리조나'],
			'US-AR' => ['en' => 'Arkansas', 'ko' => '아칸소'],
			'US-CA' => ['en' => 'California', 'ko' => '캘리포니아'],
			'US-CO' => ['en' => 'Colorado', 'ko' => '콜로라도'],
			'US-CT' => ['en' => 'Connecticut', 'ko' => '코네티컷'],
			'US-DE' => ['en' => 'Delaware', 'ko' => '델라웨어'],
			'US-DC' => ['en' => 'District of Columbia', 'ko' => '워싱턴 D.C.'],
			'US-FL' => ['en' => 'Florida', 'ko' => '플로리다'],
			'US-GA' => ['en' => 'Georgia', 'ko' => '조지아'],
			'US-HI' => ['en' => 'Hawaii', 'ko' => '하와이'],
			'US-ID' => ['en' => 'Idaho', 'ko' => '아이다호'],
			'US-IL' => ['en' => 'Illinois', 'ko' => '일리노이'],
			'US-IN' => ['en' => 'Indiana', 'ko' => '인디애나'],
			'US-IA' => ['en' => 'Iowa', 'ko' => '아이오와'],
			'US-KS' => ['en' => 'Kansas', 'ko' => '캔자스'],
			'US-KY' => ['en' => 'Kentucky', 'ko' => '켄터키'],
			'US-LA' => ['en' => 'Louisiana', 'ko' => '루이지애나'],
			'US-ME' => ['en' => 'Maine', 'ko' => '메인'],
			'US-MD' => ['en' => 'Maryland', 'ko' => '메릴랜드'],
			'US-MA' => ['en' => 'Massachusetts', 'ko' => '매사추세츠'],
			'US-MI' => ['en' => 'Michigan', 'ko' => '미시간'],
			'US-MN' => ['en' => 'Minnesota', 'ko' => '미네소타'],
			'US-MS' => ['en' => 'Mississippi', 'ko' => '미시시피'],
			'US-MO' => ['en' => 'Missouri', 'ko' => '미주리'],
			'US-MT' => ['en' => 'Montana', 'ko' => '몬태나'],
			'US-NE' => ['en' => 'Nebraska', 'ko' => '네브래스카'],
			'US-NV' => ['en' => 'Nevada', 'ko' => '네바다'],
			'US-NH' => ['en' => 'New Hampshire', 'ko' => '뉴햄프셔'],
			'US-NJ' => ['en' => 'New Jersey', 'ko' => '뉴저지'],
			'US-NM' => ['en' => 'New Mexico', 'ko' => '뉴멕시코'],
			'US-NY' => ['en' => 'New York', 'ko' => '뉴욕'],
			'US-NC' => ['en' => 'North Carolina', 'ko' => '노스캐롤라이나'],
			'US-ND' => ['en' => 'North Dakota', 'ko' => '노스다코타'],
			'US-OH' => ['en' => 'Ohio', 'ko' => '오하이오'],
			'US-OK' => ['en' => 'Oklahoma', 'ko' => '오클라호마'],
			'US-OR' => ['en' => 'Oregon', 'ko' => '오리건'],
			'US-PA' => ['en' => 'Pennsylvania', 'ko' => '펜실베이니아'],
			'US-RI' => ['en' => 'Rhode Island', 'ko' => '로드아일랜드'],
			'US-SC' => ['en' => 'South Carolina', 'ko' => '사우스캐롤라이나'],
			'US-SD' => ['en' => 'South Dakota', 'ko' => '사우스다코타'],
			'US-TN' => ['en' => 'Tennessee', 'ko' => '테네시'],
			'US-TX' => ['en' => 'Texas', 'ko' => '텍사스'],
			'US-UT' => ['en' => 'Utah', 'ko' => '유타'],
			'US-VT' => ['en' => 'Vermont', 'ko' => '버몬트'],
			'US-VA' => ['en' => 'Virginia', 'ko' => '버지니아'],
			'US-WA' => ['en' => 'Washington', 'ko' => '워싱턴'],
			'US-WV' => ['en' => 'West Virginia', 'ko' => '웨스트버지니아'],
			'US-WI' => ['en' => 'Wisconsin', 'ko' => '위스콘신'],
			'US-WY' => ['en' => 'Wyoming', 'ko' => '와이오밍'],
		],

		'CA' => [
			'CA-AB' => ['en' => 'Alberta', 'ko' => '앨버타'],
			'CA-BC' => ['en' => 'British Columbia', 'ko' => '브리티시컬럼비아'],
			'CA-MB' => ['en' => 'Manitoba', 'ko' => '매니토바'],
			'CA-NB' => ['en' => 'New Brunswick', 'ko' => '뉴브런즈윅'],
			'CA-NL' => ['en' => 'Newfoundland and Labrador', 'ko' => '뉴펀들랜드래브라도'],
			'CA-NS' => ['en' => 'Nova Scotia', 'ko' => '노바스코샤'],
			'CA-ON' => ['en' => 'Ontario', 'ko' => '온타리오'],
			'CA-PE' => ['en' => 'Prince Edward Island', 'ko' => '프린스에드워드아일랜드'],
			'CA-QC' => ['en' => 'Quebec', 'ko' => '퀘벡'],
			'CA-SK' => ['en' => 'Saskatchewan', 'ko' => '서스캐처원'],
			'CA-NT' => ['en' => 'Northwest Territories', 'ko' => '노스웨스트준주'],
			'CA-NU' => ['en' => 'Nunavut', 'ko' => '누나부트'],
			'CA-YT' => ['en' => 'Yukon', 'ko' => '유콘'],
		],

		'JP' => [
			'JP-01' => ['ja' => '北海道', 'en' => 'Hokkaido', 'ko' => '홋카이도'],
			'JP-02' => ['ja' => '青森県', 'en' => 'Aomori', 'ko' => '아오모리'],
			'JP-03' => ['ja' => '岩手県', 'en' => 'Iwate', 'ko' => '이와테'],
			'JP-04' => ['ja' => '宮城県', 'en' => 'Miyagi', 'ko' => '미야기'],
			'JP-05' => ['ja' => '秋田県', 'en' => 'Akita', 'ko' => '아키타'],
			'JP-06' => ['ja' => '山形県', 'en' => 'Yamagata', 'ko' => '야마가타'],
			'JP-07' => ['ja' => '福島県', 'en' => 'Fukushima', 'ko' => '후쿠시마'],
			'JP-08' => ['ja' => '茨城県', 'en' => 'Ibaraki', 'ko' => '이바라키'],
			'JP-09' => ['ja' => '栃木県', 'en' => 'Tochigi', 'ko' => '도치기'],
			'JP-10' => ['ja' => '群馬県', 'en' => 'Gunma', 'ko' => '군마'],
			'JP-11' => ['ja' => '埼玉県', 'en' => 'Saitama', 'ko' => '사이타마'],
			'JP-12' => ['ja' => '千葉県', 'en' => 'Chiba', 'ko' => '지바'],
			'JP-13' => ['ja' => '東京都', 'en' => 'Tokyo', 'ko' => '도쿄'],
			'JP-14' => ['ja' => '神奈川県', 'en' => 'Kanagawa', 'ko' => '가나가와'],
			'JP-15' => ['ja' => '新潟県', 'en' => 'Niigata', 'ko' => '니가타'],
			'JP-16' => ['ja' => '富山県', 'en' => 'Toyama', 'ko' => '도야마'],
			'JP-17' => ['ja' => '石川県', 'en' => 'Ishikawa', 'ko' => '이시카와'],
			'JP-18' => ['ja' => '福井県', 'en' => 'Fukui', 'ko' => '후쿠이'],
			'JP-19' => ['ja' => '山梨県', 'en' => 'Yamanashi', 'ko' => '야마나시'],
			'JP-20' => ['ja' => '長野県', 'en' => 'Nagano', 'ko' => '나가노'],
			'JP-21' => ['ja' => '岐阜県', 'en' => 'Gifu', 'ko' => '기후'],
			'JP-22' => ['ja' => '静岡県', 'en' => 'Shizuoka', 'ko' => '시즈오카'],
			'JP-23' => ['ja' => '愛知県', 'en' => 'Aichi', 'ko' => '아이치'],
			'JP-24' => ['ja' => '三重県', 'en' => 'Mie', 'ko' => '미에'],
			'JP-25' => ['ja' => '滋賀県', 'en' => 'Shiga', 'ko' => '시가'],
			'JP-26' => ['ja' => '京都府', 'en' => 'Kyoto', 'ko' => '교토'],
			'JP-27' => ['ja' => '大阪府', 'en' => 'Osaka', 'ko' => '오사카'],
			'JP-28' => ['ja' => '兵庫県', 'en' => 'Hyogo', 'ko' => '효고'],
			'JP-29' => ['ja' => '奈良県', 'en' => 'Nara', 'ko' => '나라'],
			'JP-30' => ['ja' => '和歌山県', 'en' => 'Wakayama', 'ko' => '와카야마'],
			'JP-31' => ['ja' => '鳥取県', 'en' => 'Tottori', 'ko' => '돗토리'],
			'JP-32' => ['ja' => '島根県', 'en' => 'Shimane', 'ko' => '시마네'],
			'JP-33' => ['ja' => '岡山県', 'en' => 'Okayama', 'ko' => '오카야마'],
			'JP-34' => ['ja' => '広島県', 'en' => 'Hiroshima', 'ko' => '히로시마'],
			'JP-35' => ['ja' => '山口県', 'en' => 'Yamaguchi', 'ko' => '야마구치'],
			'JP-36' => ['ja' => '徳島県', 'en' => 'Tokushima', 'ko' => '도쿠시마'],
			'JP-37' => ['ja' => '香川県', 'en' => 'Kagawa', 'ko' => '가가와'],
			'JP-38' => ['ja' => '愛媛県', 'en' => 'Ehime', 'ko' => '에히메'],
			'JP-39' => ['ja' => '高知県', 'en' => 'Kochi', 'ko' => '고치'],
			'JP-40' => ['ja' => '福岡県', 'en' => 'Fukuoka', 'ko' => '후쿠오카'],
			'JP-41' => ['ja' => '佐賀県', 'en' => 'Saga', 'ko' => '사가'],
			'JP-42' => ['ja' => '長崎県', 'en' => 'Nagasaki', 'ko' => '나가사키'],
			'JP-43' => ['ja' => '熊本県', 'en' => 'Kumamoto', 'ko' => '구마모토'],
			'JP-44' => ['ja' => '大分県', 'en' => 'Oita', 'ko' => '오이타'],
			'JP-45' => ['ja' => '宮崎県', 'en' => 'Miyazaki', 'ko' => '미야자키'],
			'JP-46' => ['ja' => '鹿児島県', 'en' => 'Kagoshima', 'ko' => '가고시마'],
			'JP-47' => ['ja' => '沖縄県', 'en' => 'Okinawa', 'ko' => '오키나와'],
		],

		'CN' => [
			'CN-BJ' => ['zh-CN' => '北京市', 'en' => 'Beijing', 'ko' => '베이징'],
			'CN-TJ' => ['zh-CN' => '天津市', 'en' => 'Tianjin', 'ko' => '톈진'],
			'CN-HE' => ['zh-CN' => '河北省', 'en' => 'Hebei', 'ko' => '허베이'],
			'CN-SX' => ['zh-CN' => '山西省', 'en' => 'Shanxi', 'ko' => '산시(산서)'],
			'CN-NM' => ['zh-CN' => '内蒙古自治区', 'en' => 'Inner Mongolia', 'ko' => '내몽골'],
			'CN-LN' => ['zh-CN' => '辽宁省', 'en' => 'Liaoning', 'ko' => '랴오닝'],
			'CN-JL' => ['zh-CN' => '吉林省', 'en' => 'Jilin', 'ko' => '지린'],
			'CN-HL' => ['zh-CN' => '黑龙江省', 'en' => 'Heilongjiang', 'ko' => '헤이룽장'],
			'CN-SH' => ['zh-CN' => '上海市', 'en' => 'Shanghai', 'ko' => '상하이'],
			'CN-JS' => ['zh-CN' => '江苏省', 'en' => 'Jiangsu', 'ko' => '장쑤'],
			'CN-ZJ' => ['zh-CN' => '浙江省', 'en' => 'Zhejiang', 'ko' => '저장'],
			'CN-AH' => ['zh-CN' => '安徽省', 'en' => 'Anhui', 'ko' => '안후이'],
			'CN-FJ' => ['zh-CN' => '福建省', 'en' => 'Fujian', 'ko' => '푸젠'],
			'CN-JX' => ['zh-CN' => '江西省', 'en' => 'Jiangxi', 'ko' => '장시'],
			'CN-SD' => ['zh-CN' => '山东省', 'en' => 'Shandong', 'ko' => '산둥'],
			'CN-HA' => ['zh-CN' => '河南省', 'en' => 'Henan', 'ko' => '허난'],
			'CN-HB' => ['zh-CN' => '湖北省', 'en' => 'Hubei', 'ko' => '후베이'],
			'CN-HN' => ['zh-CN' => '湖南省', 'en' => 'Hunan', 'ko' => '후난'],
			'CN-GD' => ['zh-CN' => '广东省', 'en' => 'Guangdong', 'ko' => '광둥'],
			'CN-GX' => ['zh-CN' => '广西壮族自治区', 'en' => 'Guangxi', 'ko' => '광시'],
			'CN-HI' => ['zh-CN' => '海南省', 'en' => 'Hainan', 'ko' => '하이난'],
			'CN-CQ' => ['zh-CN' => '重庆市', 'en' => 'Chongqing', 'ko' => '충칭'],
			'CN-SC' => ['zh-CN' => '四川省', 'en' => 'Sichuan', 'ko' => '쓰촨'],
			'CN-GZ' => ['zh-CN' => '贵州省', 'en' => 'Guizhou', 'ko' => '구이저우'],
			'CN-YN' => ['zh-CN' => '云南省', 'en' => 'Yunnan', 'ko' => '윈난'],
			'CN-XZ' => ['zh-CN' => '西藏自治区', 'en' => 'Tibet', 'ko' => '시짱(티베트)'],
			'CN-SN' => ['zh-CN' => '陕西省', 'en' => 'Shaanxi', 'ko' => '산시(섬서)'],
			'CN-GS' => ['zh-CN' => '甘肃省', 'en' => 'Gansu', 'ko' => '간쑤'],
			'CN-QH' => ['zh-CN' => '青海省', 'en' => 'Qinghai', 'ko' => '칭하이'],
			'CN-NX' => ['zh-CN' => '宁夏回族自治区', 'en' => 'Ningxia', 'ko' => '닝샤'],
			'CN-XJ' => ['zh-CN' => '新疆维吾尔自治区', 'en' => 'Xinjiang', 'ko' => '신장'],
		],

		'TW' => [
			'TW-TPE' => ['zh-TW' => '臺北市', 'en' => 'Taipei', 'ko' => '타이베이'],
			'TW-NWT' => ['zh-TW' => '新北市', 'en' => 'New Taipei', 'ko' => '신베이'],
			'TW-TAO' => ['zh-TW' => '桃園市', 'en' => 'Taoyuan', 'ko' => '타오위안'],
			'TW-TXG' => ['zh-TW' => '臺中市', 'en' => 'Taichung', 'ko' => '타이중'],
			'TW-TNN' => ['zh-TW' => '臺南市', 'en' => 'Tainan', 'ko' => '타이난'],
			'TW-KHH' => ['zh-TW' => '高雄市', 'en' => 'Kaohsiung', 'ko' => '가오슝'],
			'TW-KEE' => ['zh-TW' => '基隆市', 'en' => 'Keelung', 'ko' => '지룽'],
			'TW-HSZ' => ['zh-TW' => '新竹市', 'en' => 'Hsinchu City', 'ko' => '신주시'],
			'TW-HSQ' => ['zh-TW' => '新竹縣', 'en' => 'Hsinchu County', 'ko' => '신주현'],
			'TW-MIA' => ['zh-TW' => '苗栗縣', 'en' => 'Miaoli', 'ko' => '먀오리'],
			'TW-CHA' => ['zh-TW' => '彰化縣', 'en' => 'Changhua', 'ko' => '장화'],
			'TW-NAN' => ['zh-TW' => '南投縣', 'en' => 'Nantou', 'ko' => '난터우'],
			'TW-YUN' => ['zh-TW' => '雲林縣', 'en' => 'Yunlin', 'ko' => '윈린'],
			'TW-CYI' => ['zh-TW' => '嘉義市', 'en' => 'Chiayi City', 'ko' => '자이시'],
			'TW-CYQ' => ['zh-TW' => '嘉義縣', 'en' => 'Chiayi County', 'ko' => '자이현'],
			'TW-PIF' => ['zh-TW' => '屏東縣', 'en' => 'Pingtung', 'ko' => '핑둥'],
			'TW-ILA' => ['zh-TW' => '宜蘭縣', 'en' => 'Yilan', 'ko' => '이란'],
			'TW-HUA' => ['zh-TW' => '花蓮縣', 'en' => 'Hualien', 'ko' => '화롄'],
			'TW-TTT' => ['zh-TW' => '臺東縣', 'en' => 'Taitung', 'ko' => '타이둥'],
			'TW-PEN' => ['zh-TW' => '澎湖縣', 'en' => 'Penghu', 'ko' => '펑후'],
			'TW-KIN' => ['zh-TW' => '金門縣', 'en' => 'Kinmen', 'ko' => '진먼'],
			'TW-LIE' => ['zh-TW' => '連江縣', 'en' => 'Lienchiang', 'ko' => '롄장'],
		],

		'HK' => [
			'HK-HKI' => ['zh-TW' => '香港島', 'en' => 'Hong Kong Island', 'ko' => '홍콩섬'],
			'HK-KLN' => ['zh-TW' => '九龍', 'en' => 'Kowloon', 'ko' => '구룡'],
			'HK-NT'  => ['zh-TW' => '新界', 'en' => 'New Territories', 'ko' => '신계'],
		],

		'MX' => [
			'MX-AGU' => ['es' => 'Aguascalientes', 'en' => 'Aguascalientes', 'ko' => '아구아스칼리엔테스'],
			'MX-BCN' => ['es' => 'Baja California', 'en' => 'Baja California', 'ko' => '바하칼리포르니아'],
			'MX-BCS' => ['es' => 'Baja California Sur', 'en' => 'Baja California Sur', 'ko' => '바하칼리포르니아수르'],
			'MX-CAM' => ['es' => 'Campeche', 'en' => 'Campeche', 'ko' => '캄페체'],
			'MX-CHP' => ['es' => 'Chiapas', 'en' => 'Chiapas', 'ko' => '치아파스'],
			'MX-CHH' => ['es' => 'Chihuahua', 'en' => 'Chihuahua', 'ko' => '치와와'],
			'MX-CMX' => ['es' => 'Ciudad de México', 'en' => 'Ciudad de Mexico', 'ko' => '멕시코시티', 'alt' => 'Ciudad de Mexico'],
			'MX-COA' => ['es' => 'Coahuila de Zaragoza', 'en' => 'Coahuila de Zaragoza', 'ko' => '코아우일라'],
			'MX-COL' => ['es' => 'Colima', 'en' => 'Colima', 'ko' => '콜리마'],
			'MX-DUR' => ['es' => 'Durango', 'en' => 'Durango', 'ko' => '두랑고'],
			'MX-GUA' => ['es' => 'Guanajuato', 'en' => 'Guanajuato', 'ko' => '과나후아토'],
			'MX-GRO' => ['es' => 'Guerrero', 'en' => 'Guerrero', 'ko' => '게레로'],
			'MX-HID' => ['es' => 'Hidalgo', 'en' => 'Hidalgo', 'ko' => '이달고'],
			'MX-JAL' => ['es' => 'Jalisco', 'en' => 'Jalisco', 'ko' => '할리스코'],
			'MX-MEX' => ['es' => 'Estado de México', 'en' => 'Estado de Mexico', 'ko' => '멕시코주', 'alt' => 'Estado de Mexico'],
			'MX-MIC' => ['es' => 'Michoacán de Ocampo', 'en' => 'Michoacan de Ocampo', 'ko' => '미초아칸', 'alt' => 'Michoacan de Ocampo'],
			'MX-MOR' => ['es' => 'Morelos', 'en' => 'Morelos', 'ko' => '모렐로스'],
			'MX-NAY' => ['es' => 'Nayarit', 'en' => 'Nayarit', 'ko' => '나야리트'],
			'MX-NLE' => ['es' => 'Nuevo León', 'en' => 'Nuevo Leon', 'ko' => '누에보레온', 'alt' => 'Nuevo Leon'],
			'MX-OAX' => ['es' => 'Oaxaca', 'en' => 'Oaxaca', 'ko' => '오아하카'],
			'MX-PUE' => ['es' => 'Puebla', 'en' => 'Puebla', 'ko' => '푸에블라'],
			'MX-QUE' => ['es' => 'Querétaro', 'en' => 'Queretaro', 'ko' => '케레타로', 'alt' => 'Queretaro'],
			'MX-ROO' => ['es' => 'Quintana Roo', 'en' => 'Quintana Roo', 'ko' => '킨타나로오'],
			'MX-SLP' => ['es' => 'San Luis Potosí', 'en' => 'San Luis Potosi', 'ko' => '산루이스포토시', 'alt' => 'San Luis Potosi'],
			'MX-SIN' => ['es' => 'Sinaloa', 'en' => 'Sinaloa', 'ko' => '시날로아'],
			'MX-SON' => ['es' => 'Sonora', 'en' => 'Sonora', 'ko' => '소노라'],
			'MX-TAB' => ['es' => 'Tabasco', 'en' => 'Tabasco', 'ko' => '타바스코'],
			'MX-TAM' => ['es' => 'Tamaulipas', 'en' => 'Tamaulipas', 'ko' => '타마울리파스'],
			'MX-TLA' => ['es' => 'Tlaxcala', 'en' => 'Tlaxcala', 'ko' => '틀락스칼라'],
			'MX-VER' => ['es' => 'Veracruz de Ignacio de la Llave', 'en' => 'Veracruz de Ignacio de la Llave', 'ko' => '베라크루스'],
			'MX-YUC' => ['es' => 'Yucatán', 'en' => 'Yucatan', 'ko' => '유카탄', 'alt' => 'Yucatan'],
			'MX-ZAC' => ['es' => 'Zacatecas', 'en' => 'Zacatecas', 'ko' => '사카테카스'],
		],

		'DE' => [
			'DE-BW' => ['de' => 'Baden-Württemberg', 'en' => 'Baden-Wurttemberg', 'ko' => '바덴뷔르템베르크'],
			'DE-BY' => ['de' => 'Bayern', 'en' => 'Bavaria', 'ko' => '바이에른'],
			'DE-BE' => ['de' => 'Berlin', 'en' => 'Berlin', 'ko' => '베를린'],
			'DE-BB' => ['de' => 'Brandenburg', 'en' => 'Brandenburg', 'ko' => '브란덴부르크'],
			'DE-HB' => ['de' => 'Bremen', 'en' => 'Bremen', 'ko' => '브레멘'],
			'DE-HH' => ['de' => 'Hamburg', 'en' => 'Hamburg', 'ko' => '함부르크'],
			'DE-HE' => ['de' => 'Hessen', 'en' => 'Hesse', 'ko' => '헤센'],
			'DE-MV' => ['de' => 'Mecklenburg-Vorpommern', 'en' => 'Mecklenburg-Vorpommern', 'ko' => '메클렌부르크포어포메른'],
			'DE-NI' => ['de' => 'Niedersachsen', 'en' => 'Lower Saxony', 'ko' => '니더작센'],
			'DE-NW' => ['de' => 'Nordrhein-Westfalen', 'en' => 'North Rhine-Westphalia', 'ko' => '노르트라인베스트팔렌'],
			'DE-RP' => ['de' => 'Rheinland-Pfalz', 'en' => 'Rhineland-Palatinate', 'ko' => '라인란트팔츠'],
			'DE-SL' => ['de' => 'Saarland', 'en' => 'Saarland', 'ko' => '자를란트'],
			'DE-SN' => ['de' => 'Sachsen', 'en' => 'Saxony', 'ko' => '작센'],
			'DE-ST' => ['de' => 'Sachsen-Anhalt', 'en' => 'Saxony-Anhalt', 'ko' => '작센안할트'],
			'DE-SH' => ['de' => 'Schleswig-Holstein', 'en' => 'Schleswig-Holstein', 'ko' => '슐레스비히홀슈타인'],
			'DE-TH' => ['de' => 'Thüringen', 'en' => 'Thuringia', 'ko' => '튀링겐'],
		],

		'FR' => [
			'FR-ARA' => ['fr' => 'Auvergne-Rhône-Alpes', 'en' => 'Auvergne-Rhone-Alpes', 'ko' => '오베르뉴론알프'],
			'FR-BFC' => ['fr' => 'Bourgogne-Franche-Comté', 'en' => 'Bourgogne-Franche-Comte', 'ko' => '부르고뉴프랑슈콩테'],
			'FR-BRE' => ['fr' => 'Bretagne', 'en' => 'Brittany', 'ko' => '브르타뉴'],
			'FR-CVL' => ['fr' => 'Centre-Val de Loire', 'en' => 'Centre-Val de Loire', 'ko' => '상트르발드루아르'],
			'FR-COR' => ['fr' => 'Corse', 'en' => 'Corsica', 'ko' => '코르시카'],
			'FR-GES' => ['fr' => 'Grand Est', 'en' => 'Grand Est', 'ko' => '그랑테스트'],
			'FR-HDF' => ['fr' => 'Hauts-de-France', 'en' => 'Hauts-de-France', 'ko' => '오드프랑스'],
			'FR-IDF' => ['fr' => 'Île-de-France', 'en' => 'Ile-de-France', 'ko' => '일드프랑스'],
			'FR-NOR' => ['fr' => 'Normandie', 'en' => 'Normandy', 'ko' => '노르망디'],
			'FR-NAQ' => ['fr' => 'Nouvelle-Aquitaine', 'en' => 'Nouvelle-Aquitaine', 'ko' => '누벨아키텐'],
			'FR-OCC' => ['fr' => 'Occitanie', 'en' => 'Occitanie', 'ko' => '옥시타니'],
			'FR-PDL' => ['fr' => 'Pays de la Loire', 'en' => 'Pays de la Loire', 'ko' => '페이드라루아르'],
			'FR-PAC' => ['fr' => "Provence-Alpes-Côte d'Azur", 'en' => 'Provence-Alpes-Cote d Azur', 'ko' => '프로방스알프코트다쥐르'],
			'FR-GP'  => ['fr' => 'Guadeloupe', 'en' => 'Guadeloupe', 'ko' => '과들루프'],
			'FR-MQ'  => ['fr' => 'Martinique', 'en' => 'Martinique', 'ko' => '마르티니크'],
			'FR-GF'  => ['fr' => 'Guyane', 'en' => 'French Guiana', 'ko' => '프랑스령기아나'],
			'FR-RE'  => ['fr' => 'La Réunion', 'en' => 'Reunion', 'ko' => '레위니옹'],
			'FR-YT'  => ['fr' => 'Mayotte', 'en' => 'Mayotte', 'ko' => '마요트'],
		],

		'ES' => [
			'ES-AN' => ['es' => 'Andalucía', 'en' => 'Andalusia', 'ko' => '안달루시아'],
			'ES-AR' => ['es' => 'Aragón', 'en' => 'Aragon', 'ko' => '아라곤'],
			'ES-AS' => ['es' => 'Asturias', 'en' => 'Asturias', 'ko' => '아스투리아스'],
			'ES-IB' => ['es' => 'Illes Balears', 'en' => 'Balearic Islands', 'ko' => '발레아레스'],
			'ES-CN' => ['es' => 'Canarias', 'en' => 'Canary Islands', 'ko' => '카나리아'],
			'ES-CB' => ['es' => 'Cantabria', 'en' => 'Cantabria', 'ko' => '칸타브리아'],
			'ES-CL' => ['es' => 'Castilla y León', 'en' => 'Castile and Leon', 'ko' => '카스티야레온'],
			'ES-CM' => ['es' => 'Castilla-La Mancha', 'en' => 'Castile-La Mancha', 'ko' => '카스티야라만차'],
			'ES-CT' => ['es' => 'Cataluña', 'en' => 'Catalonia', 'ko' => '카탈루냐'],
			'ES-EX' => ['es' => 'Extremadura', 'en' => 'Extremadura', 'ko' => '엑스트레마두라'],
			'ES-GA' => ['es' => 'Galicia', 'en' => 'Galicia', 'ko' => '갈리시아'],
			'ES-RI' => ['es' => 'La Rioja', 'en' => 'La Rioja', 'ko' => '라리오하'],
			'ES-MD' => ['es' => 'Madrid', 'en' => 'Madrid', 'ko' => '마드리드'],
			'ES-MC' => ['es' => 'Murcia', 'en' => 'Murcia', 'ko' => '무르시아'],
			'ES-NC' => ['es' => 'Navarra', 'en' => 'Navarre', 'ko' => '나바라'],
			'ES-PV' => ['es' => 'País Vasco', 'en' => 'Basque Country', 'ko' => '바스크'],
			'ES-VC' => ['es' => 'Comunitat Valenciana', 'en' => 'Valencia', 'ko' => '발렌시아'],
			'ES-CE' => ['es' => 'Ceuta', 'en' => 'Ceuta', 'ko' => '세우타'],
			'ES-ML' => ['es' => 'Melilla', 'en' => 'Melilla', 'ko' => '멜리야'],
		],

		'MN' => [
			'MN-1'  => ['mn' => 'Улаанбаатар', 'en' => 'Ulaanbaatar', 'ko' => '울란바토르'],
			'MN-035' => ['mn' => 'Орхон', 'en' => 'Orkhon', 'ko' => '오르홍'],
			'MN-037' => ['mn' => 'Дархан-Уул', 'en' => 'Darkhan-Uul', 'ko' => '다르항올'],
			'MN-039' => ['mn' => 'Хэнтий', 'en' => 'Khentii', 'ko' => '헨티'],
			'MN-041' => ['mn' => 'Хөвсгөл', 'en' => 'Khuvsgul', 'ko' => '훕스굴'],
			'MN-043' => ['mn' => 'Ховд', 'en' => 'Khovd', 'ko' => '호브드'],
			'MN-046' => ['mn' => 'Увс', 'en' => 'Uvs', 'ko' => '우브스'],
			'MN-047' => ['mn' => 'Төв', 'en' => 'Tuv', 'ko' => '투브'],
			'MN-049' => ['mn' => 'Сэлэнгэ', 'en' => 'Selenge', 'ko' => '셀렝게'],
			'MN-051' => ['mn' => 'Сүхбаатар', 'en' => 'Sukhbaatar', 'ko' => '수흐바타르'],
			'MN-053' => ['mn' => 'Өмнөговь', 'en' => 'Umnugovi', 'ko' => '움느고비'],
			'MN-055' => ['mn' => 'Өвөрхангай', 'en' => 'Uvurkhangai', 'ko' => '우부르항가이'],
			'MN-057' => ['mn' => 'Завхан', 'en' => 'Zavkhan', 'ko' => '자브항'],
			'MN-059' => ['mn' => 'Дундговь', 'en' => 'Dundgovi', 'ko' => '둔드고비'],
			'MN-061' => ['mn' => 'Дорнод', 'en' => 'Dornod', 'ko' => '도르노드'],
			'MN-063' => ['mn' => 'Дорноговь', 'en' => 'Dornogovi', 'ko' => '도르노고비'],
			'MN-064' => ['mn' => 'Говьсүмбэр', 'en' => 'Govisumber', 'ko' => '고비숨베르'],
			'MN-065' => ['mn' => 'Говь-Алтай', 'en' => 'Govi-Altai', 'ko' => '고비알타이'],
			'MN-067' => ['mn' => 'Булган', 'en' => 'Bulgan', 'ko' => '불간'],
			'MN-069' => ['mn' => 'Баянхонгор', 'en' => 'Bayankhongor', 'ko' => '바양홍고르'],
			'MN-071' => ['mn' => 'Баян-Өлгий', 'en' => 'Bayan-Ulgii', 'ko' => '바양울기'],
			'MN-073' => ['mn' => 'Архангай', 'en' => 'Arkhangai', 'ko' => '아르항가이'],
		],

		'VN' => [
			'VN-HAN' => ['vi' => 'Hà Nội', 'en' => 'Hanoi', 'ko' => '하노이'],
			'VN-SGN' => ['vi' => 'Hồ Chí Minh', 'en' => 'Ho Chi Minh City', 'ko' => '호치민'],
			'VN-HPH' => ['vi' => 'Hải Phòng', 'en' => 'Haiphong', 'ko' => '하이퐁'],
			'VN-DAD' => ['vi' => 'Đà Nẵng', 'en' => 'Da Nang', 'ko' => '다낭'],
			'VN-CTO' => ['vi' => 'Cần Thơ', 'en' => 'Can Tho', 'ko' => '껀터'],
			'VN-AGI' => ['vi' => 'An Giang', 'en' => 'An Giang'],
			'VN-BGI' => ['vi' => 'Bắc Giang', 'en' => 'Bac Giang'],
			'VN-BKA' => ['vi' => 'Bắc Kạn', 'en' => 'Bac Kan'],
			'VN-BLI' => ['vi' => 'Bạc Liêu', 'en' => 'Bac Lieu'],
			'VN-BNI' => ['vi' => 'Bắc Ninh', 'en' => 'Bac Ninh'],
			'VN-BRV' => ['vi' => 'Bà Rịa - Vũng Tàu', 'en' => 'Ba Ria - Vung Tau'],
			'VN-BTR' => ['vi' => 'Bến Tre', 'en' => 'Ben Tre'],
			'VN-BDI' => ['vi' => 'Bình Định', 'en' => 'Binh Dinh'],
			'VN-BDU' => ['vi' => 'Bình Dương', 'en' => 'Binh Duong'],
			'VN-BPH' => ['vi' => 'Bình Phước', 'en' => 'Binh Phuoc'],
			'VN-BTH' => ['vi' => 'Bình Thuận', 'en' => 'Binh Thuan'],
			'VN-CMA' => ['vi' => 'Cà Mau', 'en' => 'Ca Mau'],
			'VN-CBA' => ['vi' => 'Cao Bằng', 'en' => 'Cao Bang'],
			'VN-DLA' => ['vi' => 'Đắk Lắk', 'en' => 'Dak Lak'],
			'VN-DNO' => ['vi' => 'Đắk Nông', 'en' => 'Dak Nong'],
			'VN-DBI' => ['vi' => 'Điện Biên', 'en' => 'Dien Bien'],
			'VN-DNA' => ['vi' => 'Đồng Nai', 'en' => 'Dong Nai'],
			'VN-DTH' => ['vi' => 'Đồng Tháp', 'en' => 'Dong Thap'],
			'VN-GLA' => ['vi' => 'Gia Lai', 'en' => 'Gia Lai'],
			'VN-HGI' => ['vi' => 'Hà Giang', 'en' => 'Ha Giang'],
			'VN-HNA' => ['vi' => 'Hà Nam', 'en' => 'Ha Nam'],
			'VN-HTI' => ['vi' => 'Hà Tĩnh', 'en' => 'Ha Tinh'],
			'VN-HDU' => ['vi' => 'Hải Dương', 'en' => 'Hai Duong'],
			'VN-HGA' => ['vi' => 'Hậu Giang', 'en' => 'Hau Giang'],
			'VN-HBI' => ['vi' => 'Hòa Bình', 'en' => 'Hoa Binh'],
			'VN-HYE' => ['vi' => 'Hưng Yên', 'en' => 'Hung Yen'],
			'VN-KHO' => ['vi' => 'Khánh Hòa', 'en' => 'Khanh Hoa'],
			'VN-KGI' => ['vi' => 'Kiên Giang', 'en' => 'Kien Giang'],
			'VN-KTU' => ['vi' => 'Kon Tum', 'en' => 'Kon Tum'],
			'VN-LCH' => ['vi' => 'Lai Châu', 'en' => 'Lai Chau'],
			'VN-LDO' => ['vi' => 'Lâm Đồng', 'en' => 'Lam Dong'],
			'VN-LSO' => ['vi' => 'Lạng Sơn', 'en' => 'Lang Son'],
			'VN-LCA' => ['vi' => 'Lào Cai', 'en' => 'Lao Cai'],
			'VN-LAN' => ['vi' => 'Long An', 'en' => 'Long An'],
			'VN-NDI' => ['vi' => 'Nam Định', 'en' => 'Nam Dinh'],
			'VN-NAN' => ['vi' => 'Nghệ An', 'en' => 'Nghe An'],
			'VN-NBI' => ['vi' => 'Ninh Bình', 'en' => 'Ninh Binh'],
			'VN-NTH' => ['vi' => 'Ninh Thuận', 'en' => 'Ninh Thuan'],
			'VN-PTH' => ['vi' => 'Phú Thọ', 'en' => 'Phu Tho'],
			'VN-PYE' => ['vi' => 'Phú Yên', 'en' => 'Phu Yen'],
			'VN-QBI' => ['vi' => 'Quảng Bình', 'en' => 'Quang Binh'],
			'VN-QNA' => ['vi' => 'Quảng Nam', 'en' => 'Quang Nam'],
			'VN-QNG' => ['vi' => 'Quảng Ngãi', 'en' => 'Quang Ngai'],
			'VN-QNI' => ['vi' => 'Quảng Ninh', 'en' => 'Quang Ninh'],
			'VN-QTR' => ['vi' => 'Quảng Trị', 'en' => 'Quang Tri'],
			'VN-STR' => ['vi' => 'Sóc Trăng', 'en' => 'Soc Trang'],
			'VN-SLA' => ['vi' => 'Sơn La', 'en' => 'Son La'],
			'VN-TNI' => ['vi' => 'Tây Ninh', 'en' => 'Tay Ninh'],
			'VN-TBI' => ['vi' => 'Thái Bình', 'en' => 'Thai Binh'],
			'VN-TNG' => ['vi' => 'Thái Nguyên', 'en' => 'Thai Nguyen'],
			'VN-THO' => ['vi' => 'Thanh Hóa', 'en' => 'Thanh Hoa'],
			'VN-TTH' => ['vi' => 'Thừa Thiên Huế', 'en' => 'Thua Thien Hue'],
			'VN-TGI' => ['vi' => 'Tiền Giang', 'en' => 'Tien Giang'],
			'VN-TVI' => ['vi' => 'Trà Vinh', 'en' => 'Tra Vinh'],
			'VN-TQU' => ['vi' => 'Tuyên Quang', 'en' => 'Tuyen Quang'],
			'VN-VLO' => ['vi' => 'Vĩnh Long', 'en' => 'Vinh Long'],
			'VN-VPH' => ['vi' => 'Vĩnh Phúc', 'en' => 'Vinh Phuc'],
			'VN-YBA' => ['vi' => 'Yên Bái', 'en' => 'Yen Bai'],
		],

		'TH' => [
			'TH-10' => ['en' => 'Bangkok', 'ko' => '방콕'],
			'TH-11' => ['en' => 'Samut Prakan'],
			'TH-12' => ['en' => 'Nonthaburi'],
			'TH-13' => ['en' => 'Pathum Thani'],
			'TH-14' => ['en' => 'Phra Nakhon Si Ayutthaya'],
			'TH-15' => ['en' => 'Ang Thong'],
			'TH-16' => ['en' => 'Lop Buri'],
			'TH-17' => ['en' => 'Sing Buri'],
			'TH-18' => ['en' => 'Chai Nat'],
			'TH-19' => ['en' => 'Saraburi'],
			'TH-20' => ['en' => 'Chon Buri', 'ko' => '촌부리'],
			'TH-21' => ['en' => 'Rayong'],
			'TH-22' => ['en' => 'Chanthaburi'],
			'TH-23' => ['en' => 'Trat'],
			'TH-24' => ['en' => 'Chachoengsao'],
			'TH-25' => ['en' => 'Prachin Buri'],
			'TH-26' => ['en' => 'Nakhon Nayok'],
			'TH-27' => ['en' => 'Sa Kaeo'],
			'TH-30' => ['en' => 'Nakhon Ratchasima'],
			'TH-31' => ['en' => 'Buri Ram'],
			'TH-32' => ['en' => 'Surin'],
			'TH-33' => ['en' => 'Si Sa Ket'],
			'TH-34' => ['en' => 'Ubon Ratchathani'],
			'TH-35' => ['en' => 'Yasothon'],
			'TH-36' => ['en' => 'Chaiyaphum'],
			'TH-37' => ['en' => 'Amnat Charoen'],
			'TH-38' => ['en' => 'Bueng Kan'],
			'TH-39' => ['en' => 'Nong Bua Lam Phu'],
			'TH-40' => ['en' => 'Khon Kaen'],
			'TH-41' => ['en' => 'Udon Thani'],
			'TH-42' => ['en' => 'Loei'],
			'TH-43' => ['en' => 'Nong Khai'],
			'TH-44' => ['en' => 'Maha Sarakham'],
			'TH-45' => ['en' => 'Roi Et'],
			'TH-46' => ['en' => 'Kalasin'],
			'TH-47' => ['en' => 'Sakon Nakhon'],
			'TH-48' => ['en' => 'Nakhon Phanom'],
			'TH-49' => ['en' => 'Mukdahan'],
			'TH-50' => ['en' => 'Chiang Mai', 'ko' => '치앙마이'],
			'TH-51' => ['en' => 'Lamphun'],
			'TH-52' => ['en' => 'Lampang'],
			'TH-53' => ['en' => 'Uttaradit'],
			'TH-54' => ['en' => 'Phrae'],
			'TH-55' => ['en' => 'Nan'],
			'TH-56' => ['en' => 'Phayao'],
			'TH-57' => ['en' => 'Chiang Rai'],
			'TH-58' => ['en' => 'Mae Hong Son'],
			'TH-60' => ['en' => 'Nakhon Sawan'],
			'TH-61' => ['en' => 'Uthai Thani'],
			'TH-62' => ['en' => 'Kamphaeng Phet'],
			'TH-63' => ['en' => 'Tak'],
			'TH-64' => ['en' => 'Sukhothai'],
			'TH-65' => ['en' => 'Phitsanulok'],
			'TH-66' => ['en' => 'Phichit'],
			'TH-67' => ['en' => 'Phetchabun'],
			'TH-70' => ['en' => 'Ratchaburi'],
			'TH-71' => ['en' => 'Kanchanaburi'],
			'TH-72' => ['en' => 'Suphan Buri'],
			'TH-73' => ['en' => 'Nakhon Pathom'],
			'TH-74' => ['en' => 'Samut Sakhon'],
			'TH-75' => ['en' => 'Samut Songkhram'],
			'TH-76' => ['en' => 'Phetchaburi'],
			'TH-77' => ['en' => 'Prachuap Khiri Khan'],
			'TH-80' => ['en' => 'Nakhon Si Thammarat'],
			'TH-81' => ['en' => 'Krabi', 'ko' => '끄라비'],
			'TH-82' => ['en' => 'Phangnga'],
			'TH-83' => ['en' => 'Phuket', 'ko' => '푸껫'],
			'TH-84' => ['en' => 'Surat Thani'],
			'TH-85' => ['en' => 'Ranong'],
			'TH-86' => ['en' => 'Chumphon'],
			'TH-90' => ['en' => 'Songkhla'],
			'TH-91' => ['en' => 'Satun'],
			'TH-92' => ['en' => 'Trang'],
			'TH-93' => ['en' => 'Phatthalung'],
			'TH-94' => ['en' => 'Pattani'],
			'TH-95' => ['en' => 'Yala'],
			'TH-96' => ['en' => 'Narathiwat'],
		],

		'TR' => [
			'TR-01' => ['tr' => 'Adana', 'en' => 'Adana'],
			'TR-02' => ['tr' => 'Adıyaman', 'en' => 'Adiyaman'],
			'TR-03' => ['tr' => 'Afyonkarahisar', 'en' => 'Afyonkarahisar'],
			'TR-04' => ['tr' => 'Ağrı', 'en' => 'Agri'],
			'TR-05' => ['tr' => 'Amasya', 'en' => 'Amasya'],
			'TR-06' => ['tr' => 'Ankara', 'en' => 'Ankara', 'ko' => '앙카라'],
			'TR-07' => ['tr' => 'Antalya', 'en' => 'Antalya', 'ko' => '안탈리아'],
			'TR-08' => ['tr' => 'Artvin', 'en' => 'Artvin'],
			'TR-09' => ['tr' => 'Aydın', 'en' => 'Aydin'],
			'TR-10' => ['tr' => 'Balıkesir', 'en' => 'Balikesir'],
			'TR-11' => ['tr' => 'Bilecik', 'en' => 'Bilecik'],
			'TR-12' => ['tr' => 'Bingöl', 'en' => 'Bingol'],
			'TR-13' => ['tr' => 'Bitlis', 'en' => 'Bitlis'],
			'TR-14' => ['tr' => 'Bolu', 'en' => 'Bolu'],
			'TR-15' => ['tr' => 'Burdur', 'en' => 'Burdur'],
			'TR-16' => ['tr' => 'Bursa', 'en' => 'Bursa'],
			'TR-17' => ['tr' => 'Çanakkale', 'en' => 'Canakkale'],
			'TR-18' => ['tr' => 'Çankırı', 'en' => 'Cankiri'],
			'TR-19' => ['tr' => 'Çorum', 'en' => 'Corum'],
			'TR-20' => ['tr' => 'Denizli', 'en' => 'Denizli'],
			'TR-21' => ['tr' => 'Diyarbakır', 'en' => 'Diyarbakir'],
			'TR-22' => ['tr' => 'Edirne', 'en' => 'Edirne'],
			'TR-23' => ['tr' => 'Elazığ', 'en' => 'Elazig'],
			'TR-24' => ['tr' => 'Erzincan', 'en' => 'Erzincan'],
			'TR-25' => ['tr' => 'Erzurum', 'en' => 'Erzurum'],
			'TR-26' => ['tr' => 'Eskişehir', 'en' => 'Eskisehir'],
			'TR-27' => ['tr' => 'Gaziantep', 'en' => 'Gaziantep'],
			'TR-28' => ['tr' => 'Giresun', 'en' => 'Giresun'],
			'TR-29' => ['tr' => 'Gümüşhane', 'en' => 'Gumushane'],
			'TR-30' => ['tr' => 'Hakkâri', 'en' => 'Hakkari'],
			'TR-31' => ['tr' => 'Hatay', 'en' => 'Hatay'],
			'TR-32' => ['tr' => 'Isparta', 'en' => 'Isparta'],
			'TR-33' => ['tr' => 'Mersin', 'en' => 'Mersin'],
			'TR-34' => ['tr' => 'İstanbul', 'en' => 'Istanbul', 'ko' => '이스탄불'],
			'TR-35' => ['tr' => 'İzmir', 'en' => 'Izmir', 'ko' => '이즈미르'],
			'TR-36' => ['tr' => 'Kars', 'en' => 'Kars'],
			'TR-37' => ['tr' => 'Kastamonu', 'en' => 'Kastamonu'],
			'TR-38' => ['tr' => 'Kayseri', 'en' => 'Kayseri'],
			'TR-39' => ['tr' => 'Kırklareli', 'en' => 'Kirklareli'],
			'TR-40' => ['tr' => 'Kırşehir', 'en' => 'Kirsehir'],
			'TR-41' => ['tr' => 'Kocaeli', 'en' => 'Kocaeli'],
			'TR-42' => ['tr' => 'Konya', 'en' => 'Konya'],
			'TR-43' => ['tr' => 'Kütahya', 'en' => 'Kutahya'],
			'TR-44' => ['tr' => 'Malatya', 'en' => 'Malatya'],
			'TR-45' => ['tr' => 'Manisa', 'en' => 'Manisa'],
			'TR-46' => ['tr' => 'Kahramanmaraş', 'en' => 'Kahramanmaras'],
			'TR-47' => ['tr' => 'Mardin', 'en' => 'Mardin'],
			'TR-48' => ['tr' => 'Muğla', 'en' => 'Mugla'],
			'TR-49' => ['tr' => 'Muş', 'en' => 'Mus'],
			'TR-50' => ['tr' => 'Nevşehir', 'en' => 'Nevsehir'],
			'TR-51' => ['tr' => 'Niğde', 'en' => 'Nigde'],
			'TR-52' => ['tr' => 'Ordu', 'en' => 'Ordu'],
			'TR-53' => ['tr' => 'Rize', 'en' => 'Rize'],
			'TR-54' => ['tr' => 'Sakarya', 'en' => 'Sakarya'],
			'TR-55' => ['tr' => 'Samsun', 'en' => 'Samsun'],
			'TR-56' => ['tr' => 'Siirt', 'en' => 'Siirt'],
			'TR-57' => ['tr' => 'Sinop', 'en' => 'Sinop'],
			'TR-58' => ['tr' => 'Sivas', 'en' => 'Sivas'],
			'TR-59' => ['tr' => 'Tekirdağ', 'en' => 'Tekirdag'],
			'TR-60' => ['tr' => 'Tokat', 'en' => 'Tokat'],
			'TR-61' => ['tr' => 'Trabzon', 'en' => 'Trabzon'],
			'TR-62' => ['tr' => 'Tunceli', 'en' => 'Tunceli'],
			'TR-63' => ['tr' => 'Şanlıurfa', 'en' => 'Sanliurfa'],
			'TR-64' => ['tr' => 'Uşak', 'en' => 'Usak'],
			'TR-65' => ['tr' => 'Van', 'en' => 'Van'],
			'TR-66' => ['tr' => 'Yozgat', 'en' => 'Yozgat'],
			'TR-67' => ['tr' => 'Zonguldak', 'en' => 'Zonguldak'],
			'TR-68' => ['tr' => 'Aksaray', 'en' => 'Aksaray'],
			'TR-69' => ['tr' => 'Bayburt', 'en' => 'Bayburt'],
			'TR-70' => ['tr' => 'Karaman', 'en' => 'Karaman'],
			'TR-71' => ['tr' => 'Kırıkkale', 'en' => 'Kirikkale'],
			'TR-72' => ['tr' => 'Batman', 'en' => 'Batman'],
			'TR-73' => ['tr' => 'Şırnak', 'en' => 'Sirnak'],
			'TR-74' => ['tr' => 'Bartın', 'en' => 'Bartin'],
			'TR-75' => ['tr' => 'Ardahan', 'en' => 'Ardahan'],
			'TR-76' => ['tr' => 'Iğdır', 'en' => 'Igdir'],
			'TR-77' => ['tr' => 'Yalova', 'en' => 'Yalova'],
			'TR-78' => ['tr' => 'Karabük', 'en' => 'Karabuk'],
			'TR-79' => ['tr' => 'Kilis', 'en' => 'Kilis'],
			'TR-80' => ['tr' => 'Osmaniye', 'en' => 'Osmaniye'],
			'TR-81' => ['tr' => 'Düzce', 'en' => 'Duzce'],
		],

		'RU' => [
			'RU-MOW' => ['ru' => 'Москва', 'en' => 'Moscow', 'ko' => '모스크바'],
			'RU-SPE' => ['ru' => 'Санкт-Петербург', 'en' => 'Saint Petersburg', 'ko' => '상트페테르부르크'],
			'RU-MOS' => ['ru' => 'Московская область', 'en' => 'Moscow Oblast'],
			'RU-LEN' => ['ru' => 'Ленинградская область', 'en' => 'Leningrad Oblast'],
			'RU-AD'  => ['ru' => 'Адыгея', 'en' => 'Adygea'],
			'RU-AL'  => ['ru' => 'Алтай', 'en' => 'Altai Republic'],
			'RU-ALT' => ['ru' => 'Алтайский край', 'en' => 'Altai Krai'],
			'RU-AMU' => ['ru' => 'Амурская область', 'en' => 'Amur Oblast'],
			'RU-ARK' => ['ru' => 'Архангельская область', 'en' => 'Arkhangelsk Oblast'],
			'RU-AST' => ['ru' => 'Астраханская область', 'en' => 'Astrakhan Oblast'],
			'RU-BA'  => ['ru' => 'Башкортостан', 'en' => 'Bashkortostan'],
			'RU-BEL' => ['ru' => 'Белгородская область', 'en' => 'Belgorod Oblast'],
			'RU-BRY' => ['ru' => 'Брянская область', 'en' => 'Bryansk Oblast'],
			'RU-BU'  => ['ru' => 'Бурятия', 'en' => 'Buryatia'],
			'RU-CE'  => ['ru' => 'Чечня', 'en' => 'Chechnya'],
			'RU-CHE' => ['ru' => 'Челябинская область', 'en' => 'Chelyabinsk Oblast'],
			'RU-CHU' => ['ru' => 'Чукотский АО', 'en' => 'Chukotka'],
			'RU-CU'  => ['ru' => 'Чувашия', 'en' => 'Chuvashia'],
			'RU-DA'  => ['ru' => 'Дагестан', 'en' => 'Dagestan'],
			'RU-IN'  => ['ru' => 'Ингушетия', 'en' => 'Ingushetia'],
			'RU-IRK' => ['ru' => 'Иркутская область', 'en' => 'Irkutsk Oblast'],
			'RU-IVA' => ['ru' => 'Ивановская область', 'en' => 'Ivanovo Oblast'],
			'RU-YEV' => ['ru' => 'Еврейская АО', 'en' => 'Jewish Autonomous Oblast'],
			'RU-KB'  => ['ru' => 'Кабардино-Балкария', 'en' => 'Kabardino-Balkaria'],
			'RU-KGD' => ['ru' => 'Калининградская область', 'en' => 'Kaliningrad Oblast'],
			'RU-KL'  => ['ru' => 'Калмыкия', 'en' => 'Kalmykia'],
			'RU-KLU' => ['ru' => 'Калужская область', 'en' => 'Kaluga Oblast'],
			'RU-KAM' => ['ru' => 'Камчатский край', 'en' => 'Kamchatka Krai'],
			'RU-KC'  => ['ru' => 'Карачаево-Черкесия', 'en' => 'Karachay-Cherkessia'],
			'RU-KR'  => ['ru' => 'Карелия', 'en' => 'Karelia'],
			'RU-KEM' => ['ru' => 'Кемеровская область', 'en' => 'Kemerovo Oblast'],
			'RU-KHA' => ['ru' => 'Хабаровский край', 'en' => 'Khabarovsk Krai'],
			'RU-KK'  => ['ru' => 'Хакасия', 'en' => 'Khakassia'],
			'RU-KHM' => ['ru' => 'Ханты-Мансийский АО', 'en' => 'Khanty-Mansi'],
			'RU-KIR' => ['ru' => 'Кировская область', 'en' => 'Kirov Oblast'],
			'RU-KO'  => ['ru' => 'Коми', 'en' => 'Komi'],
			'RU-KOS' => ['ru' => 'Костромская область', 'en' => 'Kostroma Oblast'],
			'RU-KDA' => ['ru' => 'Краснодарский край', 'en' => 'Krasnodar Krai'],
			'RU-KYA' => ['ru' => 'Красноярский край', 'en' => 'Krasnoyarsk Krai'],
			'RU-KGN' => ['ru' => 'Курганская область', 'en' => 'Kurgan Oblast'],
			'RU-KRS' => ['ru' => 'Курская область', 'en' => 'Kursk Oblast'],
			'RU-LIP' => ['ru' => 'Липецкая область', 'en' => 'Lipetsk Oblast'],
			'RU-MAG' => ['ru' => 'Магаданская область', 'en' => 'Magadan Oblast'],
			'RU-ME'  => ['ru' => 'Марий Эл', 'en' => 'Mari El'],
			'RU-MO'  => ['ru' => 'Мордовия', 'en' => 'Mordovia'],
			'RU-MUR' => ['ru' => 'Мурманская область', 'en' => 'Murmansk Oblast'],
			'RU-NEN' => ['ru' => 'Ненецкий АО', 'en' => 'Nenets'],
			'RU-NIZ' => ['ru' => 'Нижегородская область', 'en' => 'Nizhny Novgorod Oblast'],
			'RU-NGR' => ['ru' => 'Новгородская область', 'en' => 'Novgorod Oblast'],
			'RU-NVS' => ['ru' => 'Новосибирская область', 'en' => 'Novosibirsk Oblast'],
			'RU-OMS' => ['ru' => 'Омская область', 'en' => 'Omsk Oblast'],
			'RU-ORE' => ['ru' => 'Оренбургская область', 'en' => 'Orenburg Oblast'],
			'RU-ORL' => ['ru' => 'Орловская область', 'en' => 'Oryol Oblast'],
			'RU-PNZ' => ['ru' => 'Пензенская область', 'en' => 'Penza Oblast'],
			'RU-PER' => ['ru' => 'Пермский край', 'en' => 'Perm Krai'],
			'RU-PRI' => ['ru' => 'Приморский край', 'en' => 'Primorsky Krai'],
			'RU-PSK' => ['ru' => 'Псковская область', 'en' => 'Pskov Oblast'],
			'RU-ROS' => ['ru' => 'Ростовская область', 'en' => 'Rostov Oblast'],
			'RU-RYA' => ['ru' => 'Рязанская область', 'en' => 'Ryazan Oblast'],
			'RU-SA'  => ['ru' => 'Саха (Якутия)', 'en' => 'Sakha (Yakutia)'],
			'RU-SAK' => ['ru' => 'Сахалинская область', 'en' => 'Sakhalin Oblast'],
			'RU-SAM' => ['ru' => 'Самарская область', 'en' => 'Samara Oblast'],
			'RU-SAR' => ['ru' => 'Саратовская область', 'en' => 'Saratov Oblast'],
			'RU-SE'  => ['ru' => 'Северная Осетия', 'en' => 'North Ossetia'],
			'RU-SMO' => ['ru' => 'Смоленская область', 'en' => 'Smolensk Oblast'],
			'RU-STA' => ['ru' => 'Ставропольский край', 'en' => 'Stavropol Krai'],
			'RU-SVE' => ['ru' => 'Свердловская область', 'en' => 'Sverdlovsk Oblast'],
			'RU-TAM' => ['ru' => 'Тамбовская область', 'en' => 'Tambov Oblast'],
			'RU-TA'  => ['ru' => 'Татарстан', 'en' => 'Tatarstan'],
			'RU-TOM' => ['ru' => 'Томская область', 'en' => 'Tomsk Oblast'],
			'RU-TUL' => ['ru' => 'Тульская область', 'en' => 'Tula Oblast'],
			'RU-TY'  => ['ru' => 'Тыва', 'en' => 'Tuva'],
			'RU-TVE' => ['ru' => 'Тверская область', 'en' => 'Tver Oblast'],
			'RU-TYU' => ['ru' => 'Тюменская область', 'en' => 'Tyumen Oblast'],
			'RU-UD'  => ['ru' => 'Удмуртия', 'en' => 'Udmurtia'],
			'RU-ULY' => ['ru' => 'Ульяновская область', 'en' => 'Ulyanovsk Oblast'],
			'RU-VLA' => ['ru' => 'Владимирская область', 'en' => 'Vladimir Oblast'],
			'RU-VGG' => ['ru' => 'Волгоградская область', 'en' => 'Volgograd Oblast'],
			'RU-VLG' => ['ru' => 'Вологодская область', 'en' => 'Vologda Oblast'],
			'RU-VOR' => ['ru' => 'Воронежская область', 'en' => 'Voronezh Oblast'],
			'RU-YAN' => ['ru' => 'Ямало-Ненецкий АО', 'en' => 'Yamalo-Nenets'],
			'RU-YAR' => ['ru' => 'Ярославская область', 'en' => 'Yaroslavl Oblast'],
			'RU-ZAB' => ['ru' => 'Забайкальский край', 'en' => 'Zabaykalsky Krai'],
		],
	];

	/**
	 * 행정구역 목록이 있는 국가인지.
	 *
	 * @param string $country
	 * @return bool
	 */
	public static function has(string $country): bool
	{
		return isset(self::REGIONS[strtoupper(trim($country))]);
	}

	/**
	 * 국가의 행정구역 목록 (코드 => 현재 언어 이름).
	 *
	 * @param string $country
	 * @return array<string, string>
	 */
	public static function listOf(string $country): array
	{
		$rows = self::REGIONS[strtoupper(trim($country))] ?? [];
		$lang = (string)(\Context::getLangType() ?: 'ko');
		$out = [];
		foreach ($rows as $code => $names)
		{
			$out[$code] = $names[$lang] ?? $names['en'] ?? $code;
		}
		return $out;
	}

	/**
	 * 코드 하나의 이름. 목록에 없으면 코드를 그대로 돌려준다.
	 *
	 * @param string $code
	 * @return string
	 */
	public static function name(string $code): string
	{
		$code = trim($code);
		$country = strtoupper(substr($code, 0, 2));
		$names = self::REGIONS[$country][$code] ?? null;
		if (!is_array($names))
		{
			return $code;
		}
		$lang = (string)(\Context::getLangType() ?: 'ko');
		return $names[$lang] ?? $names['en'] ?? $code;
	}

	/**
	 * 검색용 자료. 한 줄에 코드와 모든 언어 이름을 담아 어느 표기로도 찾게 한다.
	 *
	 * @param string $country
	 * @return array<int, array{code: string, name: string, keywords: string}>
	 */
	public static function searchData(string $country): array
	{
		$rows = self::REGIONS[strtoupper(trim($country))] ?? [];
		$lang = (string)(\Context::getLangType() ?: 'ko');
		$out = [];
		foreach ($rows as $code => $names)
		{
			// alt 는 검색어일 뿐이라 이름으로 고르지 않는다 (강세 부호 없이 쳐도 찾히게 하는 값)
			$out[] = [
				'code' => $code,
				'name' => $names[$lang] ?? $names['en'] ?? $code,
				'keywords' => mb_strtolower($code . ' ' . implode(' ', $names)),
			];
		}
		return $out;
	}
}
